### ISSUE TITLE
cluster flaps in unpacking node artifact

### ISSUE THREAD

**Issue by seanjensengrey** [basho-labs/riak-mesos-executor#27]
Ocassionally we will see only a 

```
priv
lib
```

folders where the whole riak node base directory should be. When this happens we see the following errors

```
2016-08-03 00:36:40.064 [info]
	<0.122.0>@riak_mesos_executor:terminate:156 Terminating the
	executor, reasons:
	{{badmatch,{error,enoent}},[{rme_rnp,configure,3,[{file,"src/
	rme_rnp.erl"},{line,265}]},{rme_rnp,setup,1,[{file,"src/rme_rnp.
	erl"},{line,80}]},{riak_mesos_executor,launch_task,3,[{file,"src/
	riak_mesos_executor.erl"},{line,82}]},{erl_mesos_executor,call,3,
	[{file,"src/erl_mesos_executor.erl"},{line,582}]},{
	erl_mesos_executor,apply_events,2,[{file,"src/erl_mesos_executor.
	erl"},{line,513}]},{erl_mesos_executor,handle_events,2,[{file,"
	src/erl_mesos_executor.erl"},{line,501}]},{gen_server,handle_msg,
	5,[{file,"gen_server.erl"},{line,604}]},{proc_lib,init_p_do_apply
	,3,[{file,"proc_lib.erl"},{line,239}]}]}

2016-08-03 00:36:40.065 [error] <0.122.0> gen_server <0.122.0>
	terminated with reason: no match of right hand value
	{error,enoent} in rme_rnp:configure/3 line 265

2016-08-03 00:36:40.065 [error] <0.122.0> CRASH REPORT Process
	<0.122.0> with 1 neighbours exited with reason: no match of right
	hand value {error,enoent} in rme_rnp:configure/3 line 265 in
	gen_server:terminate/6 line 744

2016-08-03 00:36:40.065 [error] <0.118.0> Supervisor rme_sup had
	child riak_mesos_executor started with
	riak_mesos_executor:start_link() at <0.122.0> exit with reason no
	match of right hand value {error,enoent} in rme_rnp:configure/3
	line 265 in context child_terminated

2016-08-03 00:36:40.065 [error] <0.118.0> Supervisor rme_sup had
	child riak_mesos_executor started with
	riak_mesos_executor:start_link() at <0.122.0> exit with reason
	reached_max_restart_intensity in context shutdown

2016-08-03 00:36:40.067 [info] <0.7.0> Application
	riak_mesos_executor exited with reason: shutdown
	
	
00:46:49.024 [info] Terminating the executor, reasons:
	{{badmatch,{error,enoent}},[{rme_rnp,configure,3,[{file,"src/
	rme_rnp.erl"},{line,265}]},{rme_rnp,setup,1,[{file,"src/rme_rnp.
	erl"},{line,80}]},{riak_mesos_executor,launch_task,3,[{file,"src/
	riak_mesos_executor.erl"},{line,82}]},{erl_mesos_executor,call,3,
	[{file,"src/erl_mesos_executor.erl"},{line,582}]},{
	erl_mesos_executor,apply_events,2,[{file,"src/erl_mesos_executor.
	erl"},{line,513}]},{erl_mesos_executor,handle_events,2,[{file,"
	src/erl_mesos_executor.erl"},{line,501}]},{gen_server,handle_msg,
	5,[{file,"gen_server.erl"},{line,604}]},{proc_lib,init_p_do_apply
	,3,[{file,"proc_lib.erl"},{line,239}]}]}

00:46:49.024 [error] gen_server <0.122.0> terminated with reason: no
	match of right hand value {error,enoent} in rme_rnp:configure/3
	line 265

00:46:49.024 [error] CRASH REPORT Process <0.122.0> with 1 neighbours
	exited with reason: no match of right hand value {error,enoent}
	in rme_rnp:configure/3 line 265 in gen_server:terminate/6 line
	744

00:46:49.025 [error] Supervisor rme_sup had child riak_mesos_executor
	started with riak_mesos_executor:start_link() at <0.122.0> exit
	with reason no match of right hand value {error,enoent} in
	rme_rnp:configure/3 line 265 in context child_terminated

00:46:49.025 [error] Supervisor rme_sup had child riak_mesos_executor
	started with riak_mesos_executor:start_link() at <0.122.0> exit
	with reason reached_max_restart_intensity in context shutdown

00:46:49.026 [info] Application riak_mesos_executor exited with
	reason: shutdown

=ERROR REPORT==== 3-Aug-2016::00:46:49 ===
Server is shutdown
{"Kernel pid terminated",application_controller,"{application_terminated,riak_mesos_executor,shutdown}"}	
```

Could this be from a race condition in setting the configuration vs unpacking the assets? Can we put a debug test in the unpack phase ?

**Comment by sanmiguel** [comment]
I've seen this problem before, and tried to debug it a few times.

Some background, for anyone reading who isn't entirely familiar with this mechanism:

The fetch-and-unpack phase is handled by mesos itself, and our executor should not be started until after that completes. The correct way things should unfold is this:

```
foreach pkg in [ executor.tgz, riak.tgz, patches.tgz, explorer.tgz ]:
    fetch $pkg from scheduler
    untar $pkg

exec ./riak_mesos_executor/bin/ermf-executor
```

The contents of `executor.tgz` are listed under the `./riak_mesos_executor/` directory, so that's where they go on disk.

The remaining 3 packages all have their content listed under `./root/riak/`, which falls under the path of the persistent volume (currently always `./root`).

So mesos should first extract riak under `./root`, then inject the patches and explorer over that, into `./root/riak/lib/basho-patches/` and `./root/riak/priv/`.

When this condition kicks in, what appears to actually happen is that `executor.tgz` is correctly extracted, `riak.tgz` then appears to mesos to have been extracted but in fact never ends up on disk, and then the `patches.tgz` and `explorer.tgz` both extract correctly.

If you check the contents of the `priv` and `lib` folders, you should find that their contents are the contents of the `explorer` and `patches` archives. You should also find that the `riak` archive itself is identical to that which is served by the scheduler (i.e. not truncated or structurally invalidated in any way - you can download it and extract it normally).

If you check the `stderr` file in the affected executors you should see a series of loglines from mesos itself, where it fetches and unpacks them (seemingly successfully), then starts the executor. When I have seen this specific problem, I've never found anything suspicious in any logs, including mesos logs.

I don't think it is a coincidence that this happens when extracting an archive to the persistent disk.

I have not been able to trigger it at will at any time. But I have found that, once this symptom arises, it continues to happen for some time to all subsequent executors and even persists across new clusters and fresh RMF reinstalls.

**Comment by sanmiguel** [comment]
Re: basho-labs/riak-mesos-scheduler#82 above: I identified a bug whereby we were not specifying the archives in the correct order (the `riak` archive was being sent last, not second). This has been merged but this problem has arisen again since.

**Comment by sanmiguel** [comment]
A definite cause of this issue is if the `riak.tar.gz` archive is created without the base `./root/` path as an entry (e.g. by doing `tar zcvf riak.tar.gz root/riak/`).

I am going to run an experiment with *not* extracting riak etc into the persistent volume, and instead using that only for riak's data dir. Will report back with the findings later today.

**Comment by seanjensengrey** [comment]
I have a running cluster you could test on. Will send `ovpn` file.

**Comment by sanmiguel** [comment]
Full post mortem pending, but fix merged in Scheduler 1.6.0.

See https://gist.github.com/sanmiguel/aa06f1e6026601677af2ced87c6a35f9#file-live-upgrade-procedure-sh for the full migration procedure. Note that this is only a necessary process if destroying and recreating the cluster is unacceptable.

**Comment by sanmiguel** [comment]
@seanjensengrey I'll leave this issue open until you can confirm that 1.6.0 fixes this for you.

Also note that if you are setting a `riak.conf` for your cluster(s) you'll need to change the `platform_data_dir` value to `../../data` as per [riak.conf.default](https://github.com/basho-labs/riak-mesos-scheduler/blob/master/priv/riak.conf.default)

**Comment by sanmiguel** [comment]
Changes in the Scheduler will prevent this from happening. Closing this issue for now - if it comes up again, please reopen.
